services:
  db:
    image: postgres:16-alpine
    container_name: movie-rs
    environment:
      POSTGRES_DB: movie-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    volumes:
      - movie-db-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    restart: unless-stopped

volumes:
  movie-db-data: