ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.martdev.HttpKt.configureHttp
      - com.martdev.MonitoringKt.configureMonitoring
      - com.martdev.SerializationKt.configureSerialization
      - com.martdev.SecurityKt.configureSecurity
      - com.martdev.RequestValidationKt.configureRequestValidation
      - com.martdev.StatusPagesKt.configureStatusPages
      - com.martdev.ExposedKt.configureExposed
      - com.martdev.PostgresKt.configurePostgres
      - com.martdev.RoutingKt.configureRouting
